export const ADD_USER_TO_STORE = "STORE.ADDUSER";

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const ADD_STUDENT_TO_STORE = "STORE.ADDSTUDENT";

export const ADD_PRODUCT_TO_STORE = "STORE.ADDPRODUCT";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EDIT_CART_ITEM = "EDIT_CART_ITEM";
export const SAVE_USER_CART_SUCCESS = "SAVE_USER_CART_SUCCESS";
export const SAVE_USER_CART_FAILURE = "SAVE_USER_CART_FAILURE";
export const FETCH_USER_CART_SUCCESS = "FETCH_USER_CART_SUCCESS";
export const FETCH_USER_CART_FAILURE = "FETCH_USER_CART_FAILURE";

export const GENERATE_COUPON = "GENERATE_COUPON";

export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const SAVE_ORDER_SUCCESS = "SAVE_ORDER_SUCCESS";
export const SAVE_ORDER_FAILURE = "SAVE_ORDER_FAILURE";
export const MARK_ITEMS_CHECKED_OUT = "MARK_ITEMS_CHECKED_OUT";
export const REORDER_ORDER_SUCCESS = "REORDER_ORDER_SUCCESS";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS";

export const FETCH_USER_HOBBIES_SUCCESS = "FETCH_USER_HOBBIES_SUCCESS";
export const FETCH_USER_HOBBIES_FAILURE = "FETCH_USER_HOBBIES_FAILURE";
export const ADD_HOBBY_SUCCESS = "ADD_HOBBY_SUCCESS";
export const ADD_HOBBY_FAILURE = "ADD_HOBBY_FAILURE";

export const ADD_NOTIFICATIONS = "ADD_NOTIFICATIONS";
export const CLEAR_NOTIFICATIONS_ON_LOGOUT = "CLEAR_NOTIFICATIONS_ON_LOGOUT";
export const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
export const RESET_STATIC_NOTIFICATIONS_ON_LOGIN = "RESET_STATIC_NOTIFICATIONS_ON_LOGIN";

export const SIGN_OUT_USER = "STORE.SIGNOUTUSER";